api_connection_create:
    path: /
    methods: [POST]
    controller: App\Controller\ConnectionController::createAction

api_connection_index:
    path: /
    methods: [GET]
    controller: App\Controller\ConnectionController::indexAction

api_connection-show:
    path: /{id}
    methods: [GET]
    controller: App\Controller\ConnectionController::showAction