#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\HomeController::index

api:
    prefix: /api
    resource: "../src/Resources/config/api.yml"

views:
    resource: "../src/Resources/config/routes.yml"